AllCops:
  Exclude:
    - bin/**
    - node_modules/**/*

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/channels/application_cable/connection_test.rb
    - test/test_helper.rb

Layout/LineLength:
  Max: 120
